app1:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:8080"
app2:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8081:8080"
app3:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8082:8080"
app4:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8083:8080"